# Create wireplumber state directory under pipewire user's home (/)
d /.local                       0755 pipewire pipewire -
d /.local/state                 0755 pipewire pipewire -
d /.local/state/wireplumber     0750 pipewire pipewire -
