#@TYPE: Machine
#@NAME: Jetson Xavier NX Developer Kit (eMMC + NVMe)
#@DESCRIPTION: NVIDIA Xavier NX devkit carrier (P3509) with eMMC module.
#              Rootfs on NVMe, bootloader on QSPI/eMMC. Stock devkit DTB.

require conf/machine/jetson-xavier-nx-devkit-emmc.conf

MACHINEOVERRIDES =. "jetson-xavier-nx-banks-devkit:"

TNSPEC_BOOTDEV = "nvme0n1p1"

KERNEL_DEVICETREE = "tegra194-p3668-all-p3509-0000.dtb"

MACHINE_EXTRA_RDEPENDS:append = " banks-jetson-iface banks-audio-route"
MACHINE_FEATURES:append = " can spi"
