#!/bin/sh
if [ -f /var/lib/kiosk/desktop-mode ]; then
    exec /usr/bin/weston-terminal --maximized --shell=/etc/kiosk/kiosk-login-shell
else
    exec /usr/bin/weston-terminal --fullscreen --shell=/etc/kiosk/kiosk-media-shell
fi
